name: 'Verify Pull Request Labels'
description: 'Require labels for Pull Requests'
author: 'qameta'
inputs:
  allowed:
    required: true
    description: 'list of labels to verify'
runs:
  using: 'node12'
  main: 'dist/index.js'
